spring.application.name=ProjectPremium

spring.datasource.url=jdbc:mysql://localhost:3306/premium?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=huynh080104@gmail.com
spring.mail.password=yexjizposabc klcf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# PayOS Configuration
payos.client-id=b589bbcb-0e9e-43e8-9fa0-340c3f29024e
payos.api-key=89e7c837-7748-4a40-b5fe-f3d66703a91c
payos.checksum-key=5f9422c8d38cd4ecedb62bb797234ddc5495dc60f408fe69c3fd518c724f714c